Merlin PayPal documentation
===========================
Micromata GmbH, Kai Reinhard, Version {version}
:toc:
:toclevels: 4

:last-update-label: Copyright (C) 2018, Last updated

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== PayPal integration

Playground for an easy PayPal integration. This approach is not planned to be part of this Merlin project.

This document describes all the steps you need to integrate PayPal in your own Java application.

1. `merlin-paypal` contains some useful helper classes and demonstrates how to integrate PayPal. It's not there much magic.
2. `merlin-paypal-server` contains a ready to run command line server for testing PayPal transactions (sandbox and live).

=== How does the PayPal integration work?
1. You define a payment including prices, items etc.
2. You create this payment by publishing it to PayPal with your PayPal credentials.
3. PayPal returns a redirect url where to redirect the customer for processing the payment.
4. After the payment PayPal will callback your server (on success as well as after cancellation by the user).
5. You confirm/execute the payment by calling PayPal.

You may also refer: https://developer.paypal.com/docs/checkout/how-to/server-integration/#how-a-server-integration-works[PayPal flow diagram of a payment^]

=== Create PayPal credentials for your app
First you need credentials for testing and preparing your going-live.

1. On the https://developer.paypal.com/developer/applications[My Apps & Credentials^] page, click *Log into Dashboard*.
2. In the *REST API apps* section, click *Create App*. +
   PayPal generates a set of OAuth 2.0 client_id and secret credentials for your app for both the sandbox and the live environment.

[CAUTION]
====
Keep your credentials (client_id and secret) secret! Never ever include any credential value in your web page! +
If you need to do a PayPal call direct inside your web page, get an access token from the server first and then use this
temporarily valid access token for authentification.
====


=== Configuration of your app
Create a property file for testing.

For now, it's enough to enter the `client_id` and the `secret` you get from the previous step.

.~/.merlin-paypal
----
paypal.client_id=<YOUR APPLICATION CLIENT ID>
paypal.secret=<YOUR APPLICATION CLIENT SECRET>
----
You may name this file `.merlin-paypal` and place it in your user home directory. The Merlin server will detect this file
automatically. You may alternatively define any other filename and specify this filename with the command line option.

=== Create PayPal sandbox account
You need a sandbox account to test sandbox installations:
https://developer.paypal.com/docs/classic/lifecycle/sb_create-accounts/[create PayPal sandbox account^]

[NOTE]
====
The normal PayPal accounts aren't valid for PayPal's sandbox.
====

=== Run Merlin-PayPal server for some tests
Simply execute `de.micromata.merlin.paypal.PayPalMain` in your IDE (e. g. IntelliJ with installed Gradle plugin) or:

1. Run `gradle distZip` for a ready to run server (including Unix, MacOS and Windows start scripts).
2. Unpack the zip file (located in `merlin-paypal-server/build/distributions/`)
3. Start the server in your terminal: `bin/merlin-paypal-server` or `bin/merlin-paypal-server -f <configfile>`
4. Open your web browser: `http://localhost:8142`.

If you run the Merlin-PayPal-Server on a private host, you will be redirected to PayPal but you can't receive any call back by PayPal. For a complete testing you should
run Merlin-PayPal-Server on a public available host. Please configure the urls in the configuration file by adding the following lines:

.~/.merlin-paypal
----
...
# The urls for the Merlin-PayPal test server running on ip 159.69.120.42
paypal.return_url=http:/159.69.120.42:8142/receivePayment
paypal.cancel_url=http://159.69.120.42:8142/cancelPayment
----

=== Test the live PayPal
After successfully testing against PayPal's sandbox your may want to connect to the real world by adding the following lines:

.~/.merlin-paypal
----
# Supported modes are sandbox (default) and live:
paypal.mode=live
----


== Writing your own app
=== Configuration
You may use the PayPal configuration file from above or alternatively it's also possible to do
the config stuff in the Java code yourself.
[source,java]
----
paypalConfig = new PayPalConfig().setClientId("<client_id>").setClientSecret("<secret>")
  .setReturnUrl("<return url>").setCancelUrl("<cancel url>")
  .setMode(PayPalConfig.Mode.SANDBOX);
----

=== Java code for payments

==== Create a payment
[source,java]
----
PaymentAmount amount = new PaymentAmount(PaymentAmount.Currency.EUR).setSubtotal(29.99).setTax(5.70);
// Invoice number must be unique or null, add your shop description and the description of the item to sale.
Transaction transaction = PaymentCreator.createTransaction(amount, invoicenumber, description, itemDescription);
String href = PaymentCreator.publish(paypalConfig, transaction);
----
`href` contains the link where to redirect the user for proceeding with the payment. Through the API you may configure
more complex shopping charts including shipping costs etc.

==== Add paypal return servlets to your app
See `PaymentReceiveServlet` and `PaymentCancelServlet` of module merlin-paypal-server as example and configure these both
urls in your PayPalConfig.


==== Confirm/execute a payment

.PaymentReceiveServlet.java
[source,java]
----
Payment payment = new Payment();
payment.setId(request.getParameter("paymentId")); // Request parameter set by PayPal
PaymentExecution paymentExecution = new PaymentExecution();
paymentExecution.setPayerId(request.getParameter("PayerID"));
Payment executedPayment = payment.execute(apiContext, paymentExecution);
----

=== See a live demo
The https://demo.paypal.com/us/demo/go_platform/pcbt[demo store, window="_blank"] show how a modern integration should finally look like.
