Micromata PayPal documentation
==============================
Micromata GmbH, Kai Reinhard, Version {version}
:toc:
:toclevels: 4

:last-update-label: Copyright (C) 2018, Last updated

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== PayPal integration

This document describes all the steps you need to integrate PayPal in your own Java application.

1. `merlin-paypal` contains the core classes you need for your own PayPal integration. It's not there much magic.
2. `merlin-paypal-server` contains a ready to run command line server for testing PayPal transactions (sandbox and live).
It also contains two example servlets needed by PayPal to cancel or to confirm a payment.


=== How does the PayPal integration work?
1. You define a payment including prices, items etc.
2. You create this payment by publishing it to PayPal with your PayPal credentials.
3. PayPal returns an url where to redirect the customer for processing the payment.
4. After an successful or cancelled payment PayPal will callback your server (on success as well as after cancellation by the user).
5. You confirm/execute the payment by calling PayPal back.
6. Enjoy the money!

You may also refer: https://developer.paypal.com/docs/checkout/how-to/server-integration/#how-a-server-integration-works[PayPal flow diagram of a payment^]

=== Step 1: Create PayPal credentials for your app
First you need credentials for testing and preparing your going-live.

1. On the https://developer.paypal.com/developer/applications[My Apps & Credentials^] page, click *Log into Dashboard*.
2. In the *REST API apps* section, click *Create App*. +
   PayPal generates a set of OAuth 2.0 client_id and secret credentials for your app for both the sandbox and the live environment.

[CAUTION]
====
Keep your credentials (client_id and secret) secret! Never ever include any credential value in your web page! +
If you need to do a PayPal call direct inside your web page, get an access token from the server first and then use this
temporarily valid access token for authentification.
====


=== Step 2: Configuration of your app
Create a property file for testing.

For now, it's enough to enter the `client_id` and the `secret` you get from the previous step.

.~/.merlin-paypal
----
paypal.client_id=<YOUR APPLICATION CLIENT ID>
paypal.secret=<YOUR APPLICATION CLIENT SECRET>
----
You may name this file `.merlin-paypal` and place it in your user home directory. The Merlin server will detect this file
automatically. You may alternatively define any other filename and specify this filename with the command line option.

=== Step 3: Create PayPal sandbox account
You need a sandbox account to test sandbox installations:
https://developer.paypal.com/docs/classic/lifecycle/sb_create-accounts/[create PayPal sandbox account^]

[NOTE]
====
The normal PayPal accounts aren't valid for PayPal's sandbox.
====

=== Step 4: Run PayPal server for some tests
You may start the Paypal server in your IDE or from your command line.

==== Starting the server from your IDE
Simply execute `de.micromata.paypal.PayPalMain` in your IDE (e. g. IntelliJ with installed Gradle plugin).
You may give the optional program arguments `-f <config-file>` (see above).

==== Starting the server from your command line
1. Run `gradle distZip` for a ready to run server (including Unix, MacOS and Windows start scripts).
2. Unpack the zip file (located in `merlin-paypal-server/build/distributions/`)
3. Start the server in your terminal: `bin/merlin-paypal-server` or `bin/merlin-paypal-server -f <configfile>`
4. Open your web browser: `http://localhost:8142`.

=== Step 5: Run the server on a public available host
If you run the PayPal-Server on a private host, you will be redirected to PayPal but you can't receive any call back by PayPal. For a complete testing you should
run PayPal-Server on a public available host. Please configure the urls in the configuration file by adding the following lines:

.~/.merlin-paypal
----
...
# The urls for the PayPal test server running on ip 159.69.120.42
paypal.return_url=http:/159.69.120.42:8142/receivePayment
paypal.cancel_url=http://159.69.120.42:8142/cancelPayment
----

=== Step 6: Do live tests
After successfully testing against PayPal's sandbox your may want to connect to the real world by adding the following lines:

.~/.merlin-paypal
----
# Supported modes are sandbox (default) and live:
paypal.mode=live
----

Don't forget to replace the values `paypal.client-id` and `paypal.secret` by the live credentials of PayPal.

A final live complete configuration looks like:

.~/.merlin-paypal
----
# Supported modes are sandbox (default) and live:
paypal.mode=live
paypal.client_id=<your client id>
paypal.secret=<your client secret>
# return url called by Paypal after successful payments:
paypal.return_url=http://159.69.120.42:8142/receivePayment
# cancel url called by Paypal after cancelled payments:
paypal.cancel_url=http://159.69.120.42:8142/cancelPayment
----

[NOTE]
====
For dealing with both configurations (sandbox and live) on the same system, create both configuration files and
work e. g. with symbolic links you can easily switch: `ln -s .merlin-paypal-sandbox .merlin-paypal`
====

== Writing your own app
=== Configuration
You may use the PayPal configuration file from above or alternatively it's also possible to do
the config stuff in the Java code yourself.
[source,java]
----
paypalConfig = new PayPalConfig().setClientId("<client_id>").setClientSecret("<secret>")
  .setReturnUrl("<return url>").setCancelUrl("<cancel url>")
  .setMode(PayPalConfig.Mode.SANDBOX);
----

=== Java code for payments

==== Step 1: Create a payment
[source,java]
----
Payment payment = new Payment().setShipping(ShippingPreference.NO_SHIPPING);
Transaction transaction = new Transaction();
transaction.addItem("Merlin software", 29.99);   // The item to sell for 29.99 EUR.
Details details = new Details().setTax(5.70);    // The tax for all items.
transaction.createAmount(Currency.EUR, details); // Doesn the math for you.
transaction.setInoviceNumber("1234"); // Must be unique, can't be used twice.
payment.addTransaction(transaction);  // A payment may contain multiple transactions.
payment.setNoteToPayer("Please contact ..."); // Note to payer for important messages.
// Do the PayPal call and see the returned PaymentExecution object:
PaymentCreated paymentCreated = PayPalConnector.createPayment(paypalConfig, payment);
String redirectUrl;
if (paymentCreated != null) {
  redirectUrl = paymentCreated.getPayPalUrlForUserPayment();
  response.sendRedirect(redirectUrl); // Redirect the user to the PayPal site.
}
----
`redirectUrl` contains the link where to redirect the user for proceeding with the payment. +
Through the API you may configure
more complex shopping carts including shipping costs etc.

[NOTE]
====
This PayPal library supports chaining for creating objects and setting properties, such as: +
`new Payment().setShipping(...).addTransaction(...)`
====

==== Step 2: Add the call-backs for PayPal after the user's payment process
See `PaymentReceiveServlet` and `PaymentCancelServlet` of module merlin-paypal-server as an example and configure these both
urls in your PayPalConfig. +
(You may overwrite these default urls for every single payment, if you need payment or user specific return urls.)


==== Step 3: Confirm/execute a payment
Place this code in your servlet which PayPal calls after a user's successful payment:

.PaymentReceiveServlet.java
[source,java]
----
String paymentId = request.getParameter("paymentId"); // Request parameter given by PayPal
String payerId = request.getParameter("PayerID");
PaymentExecuted paymentExecuted = PayPalConnector.executePayment(config, paymentId, payerId);
if (paymentExecuted != null) {
  // paymentExecuted contains all information related to the PayPal payment:
  // payer, transaction, items, amounts, refund urls, time stamps etc.
}
----

=== See a live demo
The https://demo.paypal.com/us/demo/go_platform/pcbt[demo store^] show how a modern integration should finally look like.


=== Why do not use BrainSDK?
The BrainSDK seems to be behind the API. I wasn't able to set the flag `NO_SHIPPING` and the BrainSDK doesn't care about
any field restrictions (such as minimum and maximum field length or supported field values).

If you miss some functionality feel free to extend this module. It's very easy to extend calls and POJOs.

It takes only less than one day to replace BrainSDK by an own implementation for the whole payment process.

=== Project dependencies
This PayPal library is designed with a minimal set of dependencies for an light weight integration in your own app:

[%autowidth, frame="topbot",options="header"]
|=======
| Library | Version | Usage
| org.slf4j:slf4j-api|1.7.25|Common logging wrapper for compatibility with your logging framework (java logger, log4j etc.)
| com.fasterxml.jackson.core:jackson-core|2.9.7|Needed for json serialization and deserialization.
| com.fasterxml.jackson.core:jackson-annotations|2.9.7|ibid.
| com.fasterxml.jackson.core:jackson-databind|2.9.7|ibid.
|=======

Jackson is used because Gson seems not to be enough flexible for serializing and deserializing synthetic fields (such
as calculated amounts in transactions). Gson works only on field level, Jackson as well on getter methods level. +
Jackson also supports annotations to name serialized fields different from the Java
convention: e. g. field `returnUrl` -> `return_url`.

