Merlin Paypal documentation
===========================
Micromata GmbH, Kai Reinhard, Version {version}
:toc:
:toclevels: 4

:last-update-label: Copyright (C) 2018, Last updated

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== Paypal integration

Playground for dealing with PayPal integration. This is just for fun and isn't planned to be a part of Merlin.

=== Create a PayPal app
1. On the https://developer.paypal.com/developer/applications[My Apps & Credentials] page, click Log into Dashboard.
2. In the REST API apps section, click Create App. +
   PayPal generates a set of OAuth 2.0 client_id and secret credentials for your app for both the sandbox and live environments.

=== Test credentials
Create Property file:

.~/.merlin-paypal
----
paypal.
paypal.client_id=<YOUR APPLICATION CLIENT ID>
paypal.secret=<YOUR APPLICATION CLIENT SECRET>
# return url called by Paypal after successful payment:
paypal.return_url=https://example.com/your_redirect_url.html
# cancel url called by Paypal after cancelled payment:
paypal.cancel_url=https://example.com/your_cancel_url.html
----
Your may name this file `.merlin-paypal` and place it in your user directory or you may define any other filename and specify this filename with option -f:

Arguments to `de.micromata.merlin.paypal.PaypalMain`: `-f /etc/paypal.properties`.

=== Test of a payment

[source,java]
----
PaymentAmount amount = new PaymentAmount(PaymentAmount.Currency.EUR).setSubtotal(29.99).setTax(5.70);
Transaction transaction = PaymentCreator.createTransaction(amount, "Micromata T-Shirt Contest 2019");
String href = PaymentCreator.publish(paypalConfig, transaction);
----
`href` contains the link where to redirect the user for proceeding with the payment.

=== Add paypal return servlets to your app
See `PaymentReceiveServlet` and `PaymentCancelServlet` of module merlin-paypal-server as example and configure these both
urls in PaypalConfig (e. g. in properties file `~/.merlin-paypal`).

=== Do some tests with the test servlet
You may start PaypalMain (Jetty-Server) and create some test payments on calling `index.html`.

If you run the Merlin-Paypal-Server on a private host, you will be redirect to Paypal but you can't receive a call back. For a complete testing you should
run Merlin-Paypal-Server on a public available host.

=== See a live demo
The https://demo.paypal.com/us/demo/go_platform/pcbt[demo store] show how a modern integration should finally look like.
