Merlin Paypal documentation
===========================
Micromata GmbH, Kai Reinhard, Version {version}
:toc:
:toclevels: 4

:last-update-label: Copyright (C) 2018, Last updated

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== Paypal integration

Playground for dealing with PayPal integration. This is just for fun and isn't planned to be a part of Merlin.

=== Create a PayPal app
1. On the https://developer.paypal.com/developer/applications[My Apps & Credentials] page, click Log into Dashboard.
2. In the REST API apps section, click Create App. +
   PayPal generates a set of OAuth 2.0 client_id and secret credentials for your app for both the sandbox and live environments.

=== Get an access token
1. Call merlin-paypal-main:PaypalMain with arguments `-g "<client id>:<secrect>"`
2. Get the access token form the response json: `"access_token":"<access token>"`
3. Create properties file with property `paypal.access_token=<access token>`
4. Do sandbox test call merlin-paypal-main:PaypalMain with arguments `-f "property-file"` or `-a "<access token>"`

If you get a valid payment response, everything is fine for now.
