Merlin I18n converter
=====================
Micromata GmbH, Kai Reinhard
:toc:
:toclevels: 4

Copyright (C) 2018

This converter converts:

1. Java i18n property files
2. i18n Json files
3. Excel sheets (with translations) in the formats `xlsx` and `xls`.

## Download

https://sourceforge.net/projects/merlinrunner/files/merlin-i18n-converter/

## Usage

----
usage: merlin-i18n-converter [OPTIONS] [FILE1] [FILE2]...
Read i18n translations of different formats, merges and writes the
translations to different foramts.
 -b,--basename <arg>          The base name of the output files. Default
                              is 'i18n-generated'.
 -h,--help                    Print this help screen.
 -ko,--keys-only              Don't export the translations for the json
                              file, only the keys.
 -r,--read <arg>              Reads the translations of the given
                              filename. Doesn't overwrite existing
                              translations and create new keys if not
                              exist.
 -rm,--read-merge <arg>       Reads the translations of the given
                              filename. Doesn't overwrite existing
                              translations and doesn't create new keys if
                              not exist.
 -ro,--read-overwrite <arg>   Reads the translations of the given
                              filename. Does overwrite existing
                              translations and create new keys if not
                              exist.
The optional given files [FILE1] [FILE2]... will be read with the flag -r.
----

## Examples

### Converting to Excel

----
merlin-i18n-converter my-app*.properties my-app.json
----

Reads all `my-app*.properties` files (e. g. `my-app.properties`, `my-app_de.properties`,
`my-app_it.properties`) and afterwards the translations of `my-app.json`. No translation for
one key in one language will be overwritten.

The file `i18n-generated.xlsx` will be generated.
The additional created file `i18n-generated.log` contains verbose logging information of what was really done.

The property files contain the Java i18n properties, the Excel file all the translations for editing and the
json file all translations in json format.

### Converting from Excel

Edit the generated Excel file and rename it to e. g. `my-app.xlsx`.
----
merlin-i18n-converter my-app.xlsx
----

Reads all translations for all languages from the given Excel file and generates (as an example):

----
i18n-generated.json
i18n-generated.log
i18n-generated.xlsx
i18n-generated_de.properties
i18n-generated_en.properties
i18n-generated_fr.properties
i18n-generated_it.properties
----
The property files contain the Java i18n properties, the Excel file all the translations for editing and the
json file all translations in json format.

You may add the Java i18n properties or the json file to the resources of your app.

## Download ready-to-run version


## Create merlin-i18n-converter from the sources

1. `gradle distZip` generates the app including start scripts in one zip archive.
2. Unpack `build/distributions/merlin-i18n-converter-1.0.zip`and start `bin/merlin-i18n-converter` (on MacOS and Linux)
   or `bin/merlin-i18n-converter.bat` on Windows.
