Micromata PayPal server
=======================
Micromata GmbH, Kai Reinhard, Version {version}
:toc:
:toclevels: 4

:last-update-label: Copyright (C) 2018, Last updated

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== PayPal integration

Please refer module `merlin-paypal` for a more detailed documentation including a step-by-step guide.

=== Configuration
Create the PayPal default configuration file in your home directory. +
You may save this file with another name in another directory, then you have to specify this
file by starting the server with the command line option `f <config-file>`.

The example provides a configuration file for the server ip `159.69.120.42`.

.~/.merlin-paypal
----
# Supported modes are sandbox (default) and live:
paypal.mode=sandbox
paypal.client_id=<your client id>
paypal.secret=<your client secret>
# return url called by Paypal after successful payments:
paypal.return_url=http://159.69.120.42:8142/receivePayment
# cancel url called by Paypal after cancelled payments:
paypal.cancel_url=http://159.69.120.42:8142/cancelPayment
----

=== Run the PayPal server
==== Starting the server from your IDE
Simply execute `de.micromata.paypal.PayPalMain` in your IDE (e. g. IntelliJ with installed Gradle plugin).
You may give the optional program arguments `-f <config-file>` (see above).

==== Starting the server from your command line
1. Run `gradle distZip` for a ready to run server (including Unix, MacOS and Windows start scripts).
2. Unpack the zip file (located in `merlin-paypal-server/build/distributions/`)
3. Start the server in your terminal: `bin/merlin-paypal-server` or `bin/merlin-paypal-server -f <configfile>`
4. Open your web browser: `http://localhost:8142`.

