export const CONFIG_REQUESTED = 'CONFIG_REQUESTED';
export const CONFIG_RECEIVED = 'CONFIG_RECEIVED';
export const CONFIG_FETCH_FAILED = 'CONFIG_FETCH_FAILED';
export const CONFIG_CHANGED_PROPERTY = 'CONFIG_CHANGED_PROPERTY';

export const FILE_UPLOAD_STARTED = 'FILE_UPLOAD_STARTED';
export const FILE_UPLOAD_FINISHED = 'FILE_UPLOAD_FINISHED';
export const FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED';
