export const CONFIG_REQUESTED = 'CONFIG_REQUESTED';
export const CONFIG_RECEIVED = 'CONFIG_RECEIVED';
export const CONFIG_FETCH_FAILED = 'CONFIG_FETCH_FAILED';
export const CONFIG_CHANGED_PROPERTY = 'CONFIG_CHANGED_PROPERTY';

export const FILE_UPLOAD_STARTED = 'FILE_UPLOAD_STARTED';
export const FILE_UPLOAD_FINISHED = 'FILE_UPLOAD_FINISHED';
export const FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED';

export const TEMPLATE_LIST_REQUESTED = 'TEMPLATE_LIST_REQUESTED';
export const TEMPLATE_LIST_RECEIVED = 'TEMPLATE_LIST_RECEIVED';
export const TEMPLATE_LIST_REQUEST_FAILED = 'TEMPLATE_LIST_FAILED';
export const TEMPLATE_REQUESTED = 'TEMPLATE_REQUEST';
export const TEMPLATE_RECEIVED = 'TEMPLATE_RECEIVED';
export const TEMPLATE_REQUEST_FAILED = 'TEMPLATE_FAILED';
export const TEMPLATE_RUN_REQUESTED = 'TEMPLATE_RUN_REQUESTED';
export const TEMPLATE_RUN_SUCCESS = 'TEMPLATE_RUN_SUCCESS';
export const TEMPLATE_RUN_FAILED = 'TEMPLATE_RUN_FAILED';