export const CONFIG_REQUESTED = 'CONFIG_REQUESTED';
export const CONFIG_RECEIVED = 'CONFIG_RECEIVED';
export const CONFIG_SET = 'CONFIG_SET';
export const CONFIG_SET_PROPERTY = 'CONFIG_SET_PROPERTY';
